# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160822_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelisting',
            name='post_resume_or_cover',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
