# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_workskills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkSkills',
            new_name='WorkSkill',
        ),
    ]
